MND_WHITELISTED_URLS = (
    "about_me",
    "admin:mnd_duplicatepatient_add",
    "admin:mnd_duplicatepatient_autocomplete",
    "admin:mnd_duplicatepatient_change",
    "admin:mnd_duplicatepatient_changelist",
    "admin:mnd_duplicatepatient_delete",
    "admin:mnd_duplicatepatient_history",
    "carer_operations",
    "carer_registration",
    "mims_cmi_details",
    "mims_cmi_pdf",
    "mims_product_details",
    "mims_product_search",
    "mnd_health_check",
    "patient_carer_registration",
)
