# Generated by Django 2.1.10 on 2019-08-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0001_patient_registration_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatehealthfund',
            name='parent',
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='private_health_fund',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PrivateHealthFund',
        ),
    ]
