# Generated by Django 2.1.12 on 2019-10-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0002_drop_private_healt_funds_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinsurance',
            name='dva_card_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='dva_card_type',
            field=models.CharField(choices=[('', 'DVA card type'), ('Gold', 'Gold'), ('White', 'White'), ('ppbc', 'Repatriation Pharmaceutical Benefits Card')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='eligible_for_home_care',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='home_care_level',
            field=models.CharField(choices=[('', 'Care level'), ('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='ndis_coordinator_email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='needed_mac_level',
            field=models.CharField(choices=[('', 'Care level'), ('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='receiving_home_care',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='referred_for_mac_care',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
