# Generated by Django 2.2.9 on 2020-01-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0007_carer_relationship_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarycarer',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='primarycarer',
            name='relationship_info',
        ),
    ]
