# Generated by Django 2.2.9 on 2020-01-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0010_primary_carer_patients_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarycarer',
            name='patient',
        ),
    ]
