# Generated by Django 2.2.9 on 2020-01-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0011_remove_primarycarer_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carerregistration',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('registered', 'registered'), ('deactivated', 'deactivated')], default='created', max_length=16),
        ),
    ]
