# Generated by Django 2.2.9 on 2020-03-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0012_primary_carer_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerregistration',
            name='carer_email',
            field=models.EmailField(default='unset@email.com', max_length=30),
        ),
    ]
