# Generated by Django 2.2.9 on 2020-03-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0013_carerregistration_carer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarycarerrelationship',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carer_relation', to='patients.Patient'),
        ),
    ]
