# Generated by Django 2.1.15 on 2020-04-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0015_primary_carer_terminology_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinsurance',
            name='dva_card_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='DVA card number'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='dva_card_type',
            field=models.CharField(choices=[('', 'DVA card type'), ('Gold', 'Gold'), ('White', 'White'), ('ppbc', 'Repatriation Pharmaceutical Benefits Card')], default='', max_length=30, verbose_name='DVA card type'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='ndis_coordinator_email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='NDIS coordinator email'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='ndis_coordinator_first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='NDIS coordinator first name'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='ndis_coordinator_last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='NDIS coordinator last name'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='ndis_coordinator_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='NDIS coordinator phone'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='ndis_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='NDIS number'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='ndis_plan_manager',
            field=models.CharField(choices=[('', 'NDIS Plan Manager'), ('self', 'Self'), ('agency', 'Agency'), ('other', 'Other')], max_length=30, verbose_name='NDIS plan manager'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='needed_mac_level',
            field=models.CharField(choices=[('', 'Care level'), ('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four')], default='', max_length=30, verbose_name='Needed My Aged Care (MAC) level'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='referred_for_mac_care',
            field=models.BooleanField(blank=True, null=True, verbose_name='Referral for My Aged Care (MAC)'),
        ),
    ]
