# Generated by Django 2.2.10 on 2020-04-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0017_primary_carer_email_unique_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarycarer',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
