# Generated by Django 2.2.13 on 2020-09-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0018_primary_carer_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinsurance',
            name='has_dva_card',
            field=models.BooleanField(default=False, verbose_name='Do you have a DVA card?'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='has_private_health_fund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='is_ndis_eligible',
            field=models.BooleanField(default=False, verbose_name='Are you eligible for the NDIS (under 65)?'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='is_ndis_participant',
            field=models.BooleanField(default=False, verbose_name='Are you currently an NDIS participant?'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='main_hospital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='main_hospital_mrn',
            field=models.CharField(blank=True, help_text='At your main hospital attended for MND, if known', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='secondary_hospital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='secondary_hospital_mrn',
            field=models.CharField(blank=True, help_text='At your secondary hospital / health service  if known', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='primarycarer',
            name='em_contact_first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='primarycarer',
            name='em_contact_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='primarycarer',
            name='em_contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='primarycarer',
            name='is_emergency_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='dva_card_type',
            field=models.CharField(choices=[('', 'N/A'), ('Gold', 'Gold'), ('White', 'White'), ('ppbc', 'RPB')], default='', max_length=30, verbose_name='DVA card type'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='home_care_level',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='ndis_number',
            field=models.CharField(blank=True, help_text='10 digits', max_length=30, null=True, verbose_name='NDIS number'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='ndis_plan_manager',
            field=models.CharField(choices=[('self', 'Self'), ('agency', 'Agency'), ('other', 'Other')], max_length=30, verbose_name='NDIS plan manager'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='needed_mac_level',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four')], default='', max_length=30, verbose_name='Needed My Aged Care (MAC) level'),
        ),
        migrations.AlterField(
            model_name='preferredcontact',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'Phone'), ('sms', 'SMS'), ('email', 'Email'), ('primary_carer', 'Phone my Principal Caregiver'), ('emergency_contact', 'Phone my Emergency Contact'), ('person', 'Nominated person below')], max_length=30),
        ),
        migrations.AlterField(
            model_name='primarycarerrelationship',
            name='relationship',
            field=models.CharField(choices=[('', 'None'), ('spouse', 'Spouse'), ('child', 'Child'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('other', 'Other(specify)')], max_length=30),
        ),
    ]
