# Generated by Django 2.2.13 on 2020-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0018_primary_carer_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarycarer',
            name='em_contact_first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='primarycarer',
            name='em_contact_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='primarycarer',
            name='em_contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='primarycarer',
            name='is_emergency_contact',
            field=models.BooleanField(default=False),
        ),
    ]
