# Generated by Django 2.2.13 on 2020-08-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0019_primary_carer_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinsurance',
            name='main_hospital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='main_hospital_mrn',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='secondary_hospital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='secondary_hospital_mrn',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
