# Generated by Django 2.2.13 on 2020-08-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0020_patient_insurance_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinsurance',
            name='main_hospital_mrn',
            field=models.CharField(blank=True, help_text='At your main hospital attended for MND, if known', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='ndis_number',
            field=models.CharField(blank=True, help_text='10 digits', max_length=30, null=True, verbose_name='NDIS number'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='secondary_hospital_mrn',
            field=models.CharField(blank=True, help_text='At your secondary hospital / health service  if known', max_length=32, null=True),
        ),
    ]
