# Generated by Django 2.2.13 on 2020-08-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0021_patient_insurance_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarycarerrelationship',
            name='relationship',
            field=models.CharField(choices=[('', 'None'), ('spouse', 'Spouse'), ('child', 'Child'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('other', 'Other(specify)')], max_length=30),
        ),
    ]
