# Generated by Django 2.2.13 on 2020-10-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0024_mimscmicache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primarycarer',
            old_name='phone',
            new_name='mobile_phone',
        ),
        migrations.AddField(
            model_name='primarycarer',
            name='home_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
