# Generated by Django 2.2.13 on 2020-10-07 16:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0025_primary_carer_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='MIMSSearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField()),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, size=None)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='mimsproductcache',
            name='mnd_mimspro_search__5f0763_idx',
        ),
        migrations.RemoveField(
            model_name='mimsproductcache',
            name='expires_on',
        ),
        migrations.RemoveField(
            model_name='mimsproductcache',
            name='search_term',
        ),
    ]
