# Generated by Django 2.2.13 on 2020-10-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0027_clean_mims_cmi_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimscmicache',
            name='cmi_name',
            field=models.CharField(default='No name', max_length=128),
        ),
        migrations.AlterField(
            model_name='mimscmicache',
            name='cmi_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='mimscmicache',
            name='product_id',
            field=models.UUIDField(),
        ),
        migrations.AlterUniqueTogether(
            name='mimscmicache',
            unique_together={('product_id', 'cmi_id')},
        ),
    ]
