# Generated by Django 2.2.13 on 2020-10-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0028_mims_cache_model_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimsproductcache',
            name='ref_count',
            field=models.IntegerField(default=1),
        ),
    ]
