# Generated by Django 2.2.13 on 2020-12-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0030_non_required_primary_carer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarycarer',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
