# Generated by Django 2.2.13 on 2021-02-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0031_primary_carer_unique_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarycarerrelationship',
            name='relationship',
            field=models.CharField(choices=[('', ''), ('spouse', 'Spouse'), ('child', 'Child'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('other', 'Other(specify)')], max_length=30),
        ),
    ]
