# Generated by Django 2.2.24 on 2021-08-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0032_primary_carer_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinsurance',
            name='eligible_for_home_care',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='has_dva_card',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Do you have a DVA card?'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='has_private_health_fund',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='is_ndis_eligible',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Are you eligible for the NDIS (under 65)?'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='is_ndis_participant',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Are you currently an NDIS participant?'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='receiving_home_care',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='referred_for_mac_care',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Referral for My Aged Care (MAC)'),
        ),
    ]
