# Generated by Django 2.2.24 on 2021-11-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0034_remove_mims_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinsurance',
            name='ndis_number',
            field=models.CharField(blank=True, help_text='9 digits', max_length=30, null=True, verbose_name='NDIS number'),
        ),
    ]
