# Generated by Django 2.2.28 on 2022-06-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd', '0037_ndis_coordinator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carerregistration',
            name='carer_email',
            field=models.EmailField(default='unset@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='ndis_coordinator_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='NDIS coordinator email'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='ndis_coordinator_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NDIS coordinator first name'),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='ndis_coordinator_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NDIS coordinator last name'),
        ),
        migrations.AlterField(
            model_name='preferredcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='preferredcontact',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preferredcontact',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='primarycarer',
            name='em_contact_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='primarycarer',
            name='em_contact_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='primarycarer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='primarycarer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='primarycarer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
